.TH DP 1 dp
.SH NAZWA
dp \- Don't Panic
.SH SKŁADNIA
.B dp
.SH OPIS
.P
Don't Panic to prosty, lekki i modularny daemon działający w tle, napisany na konkurs Hack Heroes 2020 organizowany w ramach Code Week 2020. Jego głównym zadaniem jest wykonywanie modułów będących najczęściej skryptami powłoki (chociaż mogą być również napisane w dowolnym innym języku programowania) i przekazywanie ich standardowego wyjścia do powiadomień. Moduły najczęściej pobierają i przetwarzają dane z serwera i wypisują je na standardowe wyjście.
.P
Don't Panic jest jedynie daemonem, do jego obsługi używa się oddzielnych programów niewbudowanych w rdzeń daemona, jak np. "Don't Panic Manager" służący m.in. do konfiguracji odstępów czasowych w jakich będą wykonywane moduły oraz "Don't Panic Module Installer" służący do pobierania i usuwania modułów.
Sprawia to, że daemon podąża Filozofią UNIXa - "Pisz programy które robią jedną rzecz i robią ją dobrze. Rób programy aby pracowały ze sobą. Rób programy które łapią strumienie tekstowe, ponieważ to uniwersalny interfejs".
.SH BŁĘDY
.P
Gdy przed rozpoczęciem działania w tle wystąpi błąd, dla przykładu inny daemon działa już w tle, program wyświetli stosowny komunikat i zwróci kod błędu
.I (-1)
.SH PRAWA AUTORSKIE
Copyright (c) 2020 by:
.B Karolina Nocek,
.B Kacper Kocot,
.B Wojciech Tomasik
