.TH DPMI 1 dpmi
.SH NAZWA
dpmi \- Don't Panic Module Installer
.SH SKŁADNIA
.B dp
[-g]
[-r]
.B [lista modułów]
.SH OPIS
.P
Don't Panic Module Installer jest programem służącym do zarządzania modułami daemonu DP
.SH UŻYCIE
\fB\-g\fP
Oznacza, że chcemy zainstalować podane po fladze pakiety

\fB\-r\fP
Oznacza, że chcemy usunąć podane po fladze pakiety

Flag
.B nie wolno
mieszać ze sobą
.SH PRAWA AUTORSKIE
Copyright (c) 2020 by:
.B Karolina Nocek,
.B Kacper Kocot,
.B Wojciech Tomasik
